### PR TITLE
fix for #43

### PR DESCRIPTION
**Pull request by ColinTalbert**

### CODE REVIEW

**Comment by ColinTalbert** [comment]
I'm not sure why travis is failing, the test pass on 2.7 and 3.5 on my local machine.

**Comment by ColinTalbert** [comment]
It looks like it's failing on pip pandas.   Would porting the travis to conda be entertained?

as described here:
http://sburns.org/2014/03/28/faster-travis-builds.html

or alternately as implemented here:
https://github.com/ColinTalbert/pymdwizard/blob/master/.travis.yml


I can update the pull request to include this if you want to see it in action.

**Comment by ColinTalbert** [comment]
That seems to have restored travis:
https://travis-ci.org/ColinTalbert/pytaxize

**Comment by sckott** [comment]
thanks for this @ColinTalbert 

yeah, moving to conda is fine. 

LGTM

**Pull request merged**
