### PR TITLE
Added test for the tnrs module

### PR DESCRIPTION
**Pull request by akshayah3**

### CODE REVIEW

**Comment by sckott** [comment]
@akshayah3 looks like the test is failing for this https://travis-ci.org/sckott/pytaxize/jobs/56529863  Can you see if you can fix it

**Comment by akshayah3** [comment]
@sckott It was a problem on their server. It is working now. The tests will mostly pass now once we restart the build.

**Comment by sckott** [comment]
its the same error after restarting https://travis-ci.org/sckott/pytaxize/jobs/56529863

**Comment by akshayah3** [comment]
@sckott Tests have passed!

**Comment by sckott** [comment]
great!

**Comment by panks** [comment]
@akshayah3 Are you working on other test cases as well? If not, then let me know.

**Comment by sckott** [comment]
@akshayah3 @panks @lyttonhao  so that there is not duplicated effort, in #4  comment with what you're working on

**Pull request merged**
