### PR TITLE
Changed raise_for_status to raise_for_status()

### PR DESCRIPTION
**Pull request by akshayah3**

### CODE REVIEW

**Comment by sckott** [comment]
@akshayah3 thanks, but can you change throughout the other functions that use `raise_for_status`

**Comment by sckott** [comment]
just add those commits to this pull request

**Comment by akshayah3** [comment]
@sckott Yes I did check them throughout the code. They all seem to be defined properly everywhere except for this one. Anyways I will have a look again.

**Comment by sckott** [comment]
oh, i think you're right, sorry

**Comment by akshayah3** [comment]
Thanks for merging!

**Pull request merged**
